from __future__ import annotations

import shutil

from .config import create_mkdocs_config, write_mkdocs_config
from .copier import copy_file, copy_tree
from .links import rewrite_markdown_tree
from .navigation import build_navigation
from .paths import ProjectPaths
from .validator import validate_nav_targets


ROOT_PROJECT_FILES = {
    "ARCHITECTURE.md": "architecture.md",
    "ROADMAP.md": "roadmap.md",
    "CONTRIBUTING.md": "contributing.md",
    "CODE_OF_CONDUCT.md": "code-of-conduct.md",
    "CHANGELOG.md": "changelog.md",
}

ROOT_DOC_FILES = (
    "disclaimer.md",
    "reference-options.md",
    "repository-map.md",
    "tech-stack.md",
)


def reset_output(paths: ProjectPaths) -> None:
    if paths.generated.exists():
        shutil.rmtree(paths.generated)

    paths.generated.mkdir(parents=True)


def stage_sources(paths: ProjectPaths) -> None:
    copy_file(paths.root / "README.md", paths.generated / "index.md")

    for source_name, target_name in ROOT_PROJECT_FILES.items():
        copy_file(
            paths.root / source_name,
            paths.generated / "project" / target_name,
        )

    copy_tree(paths.root / "standard", paths.generated / "standards")
    copy_tree(paths.root / "reference", paths.generated / "reference-houses")
    copy_tree(paths.docs / "adr", paths.generated / "adr")
    copy_tree(paths.docs / "project", paths.generated / "project")
    copy_tree(paths.docs / "workflows", paths.generated / "workflows")
    copy_tree(paths.docs / "checklists", paths.generated / "checklists")
    copy_tree(paths.docs / "images", paths.generated / "images")

    for filename in ROOT_DOC_FILES:
        copy_file(
            paths.docs / filename,
            paths.generated / "project" / filename,
        )

    (paths.generated / ".generated").write_text(
        "Generated by the OHS documentation builder. "
        "Do not edit directly.\n",
        encoding="utf-8",
    )


def build(paths: ProjectPaths) -> None:
    reset_output(paths)
    stage_sources(paths)
    rewrite_markdown_tree(paths.generated)

    nav = build_navigation(paths.generated)
    config = create_mkdocs_config(nav)

    write_mkdocs_config(paths.mkdocs, config)
    validate_nav_targets(paths.mkdocs, paths.generated)
