#!/usr/bin/env bash
set -euo pipefail

# replace-docs-builder-with-link-rewrite.sh
#
# Replaces src/ohs/docs/builder.py with the canonical implementation and
# installs Markdown link rewriting. This avoids patching assumptions.

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT"

for required in \
  src/ohs/docs/config.py \
  src/ohs/docs/copier.py \
  src/ohs/docs/navigation.py \
  src/ohs/docs/paths.py \
  src/ohs/docs/validator.py \
  src/ohs/docs/naming.py
do
  if [[ ! -f "$required" ]]; then
    echo "[!] Missing required file: $required"
    exit 1
  fi
done

cp src/ohs/docs/builder.py src/ohs/docs/builder.py.before-link-rewrite

cat > src/ohs/docs/links.py <<'PY'
from __future__ import annotations

import re
from pathlib import Path, PurePosixPath
from urllib.parse import urlsplit, urlunsplit

from .naming import slugify_component

_INLINE_LINK = re.compile(
    r"(?P<prefix>!?\[[^\]]*\]\()"
    r"(?P<target>[^)\s]+)"
    r"(?P<suffix>(?:\s+['\"][^'\"]*['\"])?\))"
)


def normalize_relative_target(target: str) -> str:
    """Normalize the path portion of a relative Markdown link."""

    if target.startswith(("#", "mailto:", "tel:", "data:")):
        return target

    parsed = urlsplit(target)

    if parsed.scheme or parsed.netloc or not parsed.path or parsed.path.startswith("/"):
        return target

    path = PurePosixPath(parsed.path)
    normalized = "/".join(
        slugify_component(part)
        for part in path.parts
        if part not in ("", ".")
    )

    if parsed.path.startswith("./"):
        normalized = f"./{normalized}"

    return urlunsplit(("", "", normalized, parsed.query, parsed.fragment))


def rewrite_markdown_links(text: str) -> str:
    """Rewrite relative inline Markdown links and image references."""

    def replace(match: re.Match[str]) -> str:
        return (
            match.group("prefix")
            + normalize_relative_target(match.group("target"))
            + match.group("suffix")
        )

    return _INLINE_LINK.sub(replace, text)


def rewrite_markdown_tree(root: Path) -> None:
    """Rewrite relative links in all generated Markdown files."""

    for path in root.rglob("*.md"):
        if not path.is_file():
            continue

        original = path.read_text(encoding="utf-8")
        rewritten = rewrite_markdown_links(original)

        if rewritten != original:
            path.write_text(rewritten, encoding="utf-8")
PY

cat > src/ohs/docs/builder.py <<'PY'
from __future__ import annotations

import shutil

from .config import mkdocs_configuration, write_mkdocs_configuration
from .copier import copy_file, copy_tree
from .links import rewrite_markdown_tree
from .navigation import build_navigation
from .paths import ProjectPaths
from .validator import validate_nav_targets


ROOT_PROJECT_FILES = {
    "ARCHITECTURE.md": "architecture.md",
    "ROADMAP.md": "roadmap.md",
    "CONTRIBUTING.md": "contributing.md",
    "CODE_OF_CONDUCT.md": "code-of-conduct.md",
    "CHANGELOG.md": "changelog.md",
}

ROOT_DOC_FILES = (
    "disclaimer.md",
    "reference-options.md",
    "repository-map.md",
    "tech-stack.md",
)


def reset_output(paths: ProjectPaths) -> None:
    """Remove and recreate the generated documentation directory."""

    if paths.generated.exists():
        shutil.rmtree(paths.generated)

    paths.generated.mkdir(parents=True)


def stage_sources(paths: ProjectPaths) -> None:
    """Copy canonical repository content into the generated docs tree."""

    copy_file(paths.root / "README.md", paths.generated / "index.md")

    for source_name, target_name in ROOT_PROJECT_FILES.items():
        copy_file(
            paths.root / source_name,
            paths.generated / "project" / target_name,
        )

    copy_tree(paths.root / "standard", paths.generated / "standards")
    copy_tree(
        paths.root / "reference",
        paths.generated / "reference-houses",
    )
    copy_tree(paths.docs / "adr", paths.generated / "adr")
    copy_tree(paths.docs / "project", paths.generated / "project")
    copy_tree(paths.docs / "workflows", paths.generated / "workflows")
    copy_tree(paths.docs / "checklists", paths.generated / "checklists")
    copy_tree(paths.docs / "images", paths.generated / "images")

    for filename in ROOT_DOC_FILES:
        copy_file(
            paths.docs / filename,
            paths.generated / "project" / filename,
        )

    (paths.generated / ".generated").write_text(
        "Generated by the OHS documentation builder. "
        "Do not edit directly.\n",
        encoding="utf-8",
    )


def build(paths: ProjectPaths) -> None:
    """Generate documentation sources, navigation, and MkDocs config."""

    reset_output(paths)
    stage_sources(paths)

    # Generated paths are normalized by copier.py. Rewrite relative links
    # accordingly before MkDocs validates them.
    rewrite_markdown_tree(paths.generated)

    navigation = build_navigation(paths.generated)
    configuration = mkdocs_configuration(navigation)

    write_mkdocs_configuration(paths.mkdocs, configuration)
    validate_nav_targets(paths.mkdocs, paths.generated)
PY

cat > tests/docs/test_links.py <<'PY'
from ohs.docs.links import normalize_relative_target, rewrite_markdown_links


def test_normalizes_relative_target() -> None:
    assert (
        normalize_relative_target("OHS-000/README.md")
        == "ohs-000/readme.md"
    )


def test_preserves_fragment() -> None:
    assert (
        normalize_relative_target("OHS-001/README.md#Scope")
        == "ohs-001/readme.md#Scope"
    )


def test_preserves_external_url() -> None:
    url = "https://example.org/OHS-000/README.md"
    assert normalize_relative_target(url) == url


def test_rewrites_markdown_link() -> None:
    source = "[Editorial Guide](OHS-000/README.md)"
    expected = "[Editorial Guide](ohs-000/readme.md)"
    assert rewrite_markdown_links(source) == expected


def test_rewrites_image_link() -> None:
    source = "![Plan](Images/House_Plan.PNG)"
    expected = "![Plan](images/house-plan.png)"
    assert rewrite_markdown_links(source) == expected


def test_preserves_anchor_only_link() -> None:
    source = "[Scope](#scope)"
    assert rewrite_markdown_links(source) == source
PY

echo "[*] Running tests..."
uv run pytest tests/docs

echo "[*] Running strict documentation build..."
uv run ohs-build-docs --strict

echo
echo "[✓] Canonical builder installed and link rewriting enabled."
echo
echo "A backup is available at:"
echo "  src/ohs/docs/builder.py.before-link-rewrite"
echo
echo "Next:"
echo "  git status"
echo "  git diff --stat"
echo "  git diff"
echo "  git add -A"
echo '  git commit -m "Add normalized documentation link rewriting"'
echo "  git push origin $(git branch --show-current)"
